import { ChatRoom, Message } from "../types/chat";
import { User } from "../types/auth";
import { Client } from "../types/client";
import { Appointment } from "../types/appointment";
import { Task } from "../types/task";

export const mockUsers: User[] = [
  { id: 1, firstName: "Анна", lastName: "Иванова", role: "CLIENT" },
  { id: 2, firstName: "Игорь", lastName: "Смирнов", role: "CLIENT" },
  { id: 3, firstName: "Мария", lastName: "Кузнецова", role: "CLIENT" },
  { id: 4, firstName: "Дмитрий", lastName: "Попов", role: "CLIENT" },
  { id: 5, firstName: "Елена", lastName: "Новикова", role: "CLIENT" },
  { id: 6, firstName: "Алексей", lastName: "Соколов", role: "CLIENT" },
  { id: 7, firstName: "Ольга", lastName: "Лебедева", role: "CLIENT" },
  { id: 8, firstName: "Николай", lastName: "Козлов", role: "CLIENT" },
  { id: 9, firstName: "Татьяна", lastName: "Морозова", role: "CLIENT" },
  { id: 10, firstName: "Сергей", lastName: "Петров", role: "CLIENT" },
  { id: 11, firstName: "Ирина", lastName: "Васильева", role: "CLIENT" },
  { id: 12, firstName: "Владимир", lastName: "Михайлов", role: "CLIENT" },
  { id: 13, firstName: "Вася", lastName: "Пупкин", role: "CLIENT" },
  { id: 14, firstName: "Людмила", lastName: "Федорова", role: "CLIENT" },
  { id: 15, firstName: "Павел", lastName: "Сидоров", role: "CLIENT" },
  { id: 16, firstName: "Екатерина", lastName: "Никитина", role: "CLIENT" },
  { id: 17, firstName: "Максим", lastName: "Горбунов", role: "CLIENT" },
  { id: 18, firstName: "Оксана", lastName: "Белова", role: "CLIENT" },
  { id: 19, firstName: "Роман", lastName: "Жуков", role: "CLIENT" },
  { id: 20, firstName: "Светлана", lastName: "Крылова", role: "CLIENT" },
  { id: 21, firstName: "Денис", lastName: "Морозов", role: "CLIENT" },
  { id: 22, firstName: "Алёна", lastName: "Волкова", role: "CLIENT" },
  { id: 23, firstName: "Константин", lastName: "Данилов", role: "CLIENT" },
  { id: 24, firstName: "Наталья", lastName: "Соколова", role: "CLIENT" },
  { id: 25, firstName: "Андрей", lastName: "Ковалев", role: "CLIENT" },
  {
    id: 101,
    firstName: "Александр",
    lastName: "Сергеев",
    role: "PSYCHOLOGIST",
  },
  { id: 102, firstName: "Наталья", lastName: "Громова", role: "PSYCHOLOGIST" },
  { id: 103, firstName: "Евгений", lastName: "Кузьмин", role: "PSYCHOLOGIST" },
  { id: 104, firstName: "Ольга", lastName: "Журавлева", role: "PSYCHOLOGIST" },
  { id: 105, firstName: "Павел", lastName: "Сидоров", role: "PSYCHOLOGIST" },
  { id: 106, firstName: "Анна", lastName: "Дорофеева", role: "PSYCHOLOGIST" },
  { id: 107, firstName: "Иван", lastName: "Петров", role: "PSYCHOLOGIST" },
  { id: 108, firstName: "Марина", lastName: "Федорова", role: "PSYCHOLOGIST" },
  {
    id: 109,
    firstName: "Константин",
    lastName: "Волков",
    role: "PSYCHOLOGIST",
  },
  { id: 110, firstName: "Елена", lastName: "Мельникова", role: "PSYCHOLOGIST" },
  { id: 111, firstName: "Денис", lastName: "Морозов", role: "PSYCHOLOGIST" },
  { id: 112, firstName: "Светлана", lastName: "Климова", role: "PSYCHOLOGIST" },
  {
    id: 1709255700,
    firstName: "Юрий",
    lastName: "Буторин",
    role: "PSYCHOLOGIST",
  },
];

export const mockClients: Client[] = [
  { id: 1, firstName: "Анна", lastName: "Иванова" },
  { id: 2, firstName: "Игорь", lastName: "Смирнов" },
  { id: 3, firstName: "Мария", lastName: "Кузнецова" },
  { id: 4, firstName: "Дмитрий", lastName: "Попов" },
  { id: 5, firstName: "Елена", lastName: "Новикова" },
  { id: 6, firstName: "Алексей", lastName: "Соколов" },
  { id: 7, firstName: "Ольга", lastName: "Лебедева" },
  { id: 8, firstName: "Николай", lastName: "Козлов" },
  { id: 9, firstName: "Татьяна", lastName: "Морозова" },
  { id: 10, firstName: "Сергей", lastName: "Петров" },
  { id: 11, firstName: "Find", lastName: "Me" },
  { id: 12, firstName: "Ирина", lastName: "Васильева" },
  { id: 13, firstName: "Вася", lastName: "Пупкин" },
  { id: 14, firstName: "Людмила", lastName: "Никитина" },
  { id: 15, firstName: "Георгий", lastName: "Орлов" },
  { id: 16, firstName: "Алина", lastName: "Егорова" },
  { id: 17, firstName: "Владимир", lastName: "Гусев" },
  { id: 18, firstName: "Ксения", lastName: "Михайлова" },
  { id: 19, firstName: "Максим", lastName: "Зайцев" },
  { id: 20, firstName: "Екатерина", lastName: "Соколова" },
  { id: 21, firstName: "Андрей", lastName: "Титов" },
  { id: 22, firstName: "Оксана", lastName: "Романова" },
  { id: 23, firstName: "Роман", lastName: "Крылов" },
  { id: 24, firstName: "Дарья", lastName: "Воронова" },
  { id: 25, firstName: "Илья", lastName: "Коновалов" },
];

export const mockChatRooms: ChatRoom[] = [
  { id: 1, participant1Id: 1, participant2Id: 1709255700 },
  { id: 2, participant1Id: 2, participant2Id: 1709255700 },
  { id: 3, participant1Id: 3, participant2Id: 1709255700 },
  { id: 4, participant1Id: 4, participant2Id: 1709255700 },
  { id: 5, participant1Id: 5, participant2Id: 1709255700 },
  { id: 6, participant1Id: 6, participant2Id: 1709255700 },
  { id: 7, participant1Id: 7, participant2Id: 1709255700 },
  { id: 8, participant1Id: 8, participant2Id: 1709255700 },
  { id: 9, participant1Id: 9, participant2Id: 1709255700 },
  { id: 10, participant1Id: 10, participant2Id: 1709255700 },
  { id: 11, participant1Id: 11, participant2Id: 1709255700 },
  { id: 12, participant1Id: 12, participant2Id: 1709255700 },
  { id: 13, participant1Id: 13, participant2Id: 1709255700 },
  { id: 14, participant1Id: 14, participant2Id: 1709255700 },
  { id: 15, participant1Id: 15, participant2Id: 1709255700 },
  { id: 16, participant1Id: 16, participant2Id: 1709255700 },
  { id: 17, participant1Id: 17, participant2Id: 1709255700 },
  { id: 18, participant1Id: 18, participant2Id: 1709255700 },
  { id: 19, participant1Id: 19, participant2Id: 1709255700 },
  { id: 20, participant1Id: 20, participant2Id: 1709255700 },
  { id: 21, participant1Id: 21, participant2Id: 1709255700 },
  { id: 22, participant1Id: 22, participant2Id: 1709255700 },
  { id: 23, participant1Id: 23, participant2Id: 1709255700 },
  { id: 24, participant1Id: 24, participant2Id: 1709255700 },
  { id: 25, participant1Id: 25, participant2Id: 1709255700 },
];

export const mockMessages: Message[] = [
  {
    id: 1,
    roomId: 1,
    senderId: 1,
    text: "Здравствуйте!",
    timestamp: new Date().toISOString(),
  },
  {
    id: 2,
    roomId: 1,
    senderId: 1709255700,
    text: "Добрый день, чем могу помочь?",
    timestamp: new Date().toISOString(),
  },
  {
    id: 3,
    roomId: 2,
    senderId: 2,
    text: "Привет!",
    timestamp: new Date().toISOString(),
  },
  {
    id: 4,
    roomId: 2,
    senderId: 1709255700,
    text: "Здравствуйте!",
    timestamp: new Date().toISOString(),
  },
  {
    id: 5,
    roomId: 3,
    senderId: 3,
    text: "Нужна консультация.",
    timestamp: new Date().toISOString(),
  },
  {
    id: 6,
    roomId: 3,
    senderId: 1709255700,
    text: "Готов помочь.",
    timestamp: new Date().toISOString(),
  },
  {
    id: 7,
    roomId: 4,
    senderId: 4,
    text: "Здравствуйте, есть время?",
    timestamp: new Date().toISOString(),
  },
  {
    id: 8,
    roomId: 4,
    senderId: 1709255700,
    text: "Да, расскажите подробнее.",
    timestamp: new Date().toISOString(),
  },
  {
    id: 9,
    roomId: 5,
    senderId: 5,
    text: "Спасибо за помощь!",
    timestamp: new Date().toISOString(),
  },
  {
    id: 10,
    roomId: 5,
    senderId: 1709255700,
    text: "Рад помочь!",
    timestamp: new Date().toISOString(),
  },
  // дополнительные сообщения для объема
  {
    id: 11,
    roomId: 6,
    senderId: 6,
    text: "Как проходит сеанс?",
    timestamp: new Date().toISOString(),
  },
  {
    id: 12,
    roomId: 6,
    senderId: 1709255700,
    text: "Все идет хорошо.",
    timestamp: new Date().toISOString(),
  },
  {
    id: 13,
    roomId: 7,
    senderId: 7,
    text: "Можно ли перенести встречу?",
    timestamp: new Date().toISOString(),
  },
  {
    id: 14,
    roomId: 7,
    senderId: 1709255700,
    text: "Да, на какой день?",
    timestamp: new Date().toISOString(),
  },
  {
    id: 15,
    roomId: 8,
    senderId: 8,
    text: "Хочу записаться на консультацию.",
    timestamp: new Date().toISOString(),
  },
  {
    id: 16,
    roomId: 8,
    senderId: 1709255700,
    text: "Отлично, выбирайте время.",
    timestamp: new Date().toISOString(),
  },
  {
    id: 17,
    roomId: 9,
    senderId: 9,
    text: "Спасибо за поддержку!",
    timestamp: new Date().toISOString(),
  },
  {
    id: 18,
    roomId: 9,
    senderId: 1709255700,
    text: "Всегда пожалуйста.",
    timestamp: new Date().toISOString(),
  },
  {
    id: 19,
    roomId: 10,
    senderId: 10,
    text: "Как вы себя чувствуете?",
    timestamp: new Date().toISOString(),
  },
  {
    id: 20,
    roomId: 10,
    senderId: 1709255700,
    text: "Лучше, спасибо.",
    timestamp: new Date().toISOString(),
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 1,
    date: "2025-06-13",
    startTime: "18:00",
    endTime: "19:00",
    clientId: 8,
  },
  {
    id: 2,
    date: "2025-06-14",
    startTime: "16:00",
    endTime: "17:00",
    clientId: 9,
  },
  {
    id: 3,
    date: "2025-06-15",
    startTime: "14:00",
    endTime: "15:00",
    clientId: 1,
  },
  {
    id: 4,
    date: "2025-06-16",
    startTime: "10:00",
    endTime: "11:00",
    clientId: 2,
  },
  {
    id: 5,
    date: "2025-06-17",
    startTime: "13:00",
    endTime: "14:00",
    clientId: 3,
  },
  {
    id: 6,
    date: "2025-06-18",
    startTime: "09:00",
    endTime: "10:00",
    clientId: 4,
  },
  {
    id: 7,
    date: "2025-06-19",
    startTime: "15:00",
    endTime: "16:00",
    clientId: 5,
  },
  {
    id: 8,
    date: "2025-06-20",
    startTime: "11:00",
    endTime: "12:00",
    clientId: 6,
  },
  {
    id: 9,
    date: "2025-06-21",
    startTime: "17:00",
    endTime: "18:00",
    clientId: 7,
  },
  {
    id: 10,
    date: "2025-06-22",
    startTime: "12:00",
    endTime: "13:00",
    clientId: 10,
  },
  {
    id: 11,
    date: "2025-06-23",
    startTime: "14:30",
    endTime: "15:30",
    clientId: 11,
  },
  {
    id: 12,
    date: "2025-06-24",
    startTime: "09:30",
    endTime: "10:30",
    clientId: 12,
  },
  {
    id: 13,
    date: "2025-06-25",
    startTime: "16:00",
    endTime: "17:00",
    clientId: 13,
  },
  {
    id: 14,
    date: "2025-06-26",
    startTime: "10:00",
    endTime: "11:00",
    clientId: 14,
  },
  {
    id: 15,
    date: "2025-06-27",
    startTime: "11:30",
    endTime: "12:30",
    clientId: 15,
  },
  {
    id: 16,
    date: "2025-06-28",
    startTime: "13:00",
    endTime: "14:00",
    clientId: 16,
  },
  {
    id: 17,
    date: "2025-06-29",
    startTime: "15:00",
    endTime: "16:00",
    clientId: 17,
  },
  {
    id: 18,
    date: "2025-06-30",
    startTime: "09:00",
    endTime: "10:00",
    clientId: 18,
  },
  {
    id: 19,
    date: "2025-07-01",
    startTime: "14:00",
    endTime: "15:00",
    clientId: 19,
  },
  {
    id: 20,
    date: "2025-07-02",
    startTime: "10:00",
    endTime: "11:00",
    clientId: 20,
  },
  {
    id: 21,
    date: "2025-07-03",
    startTime: "16:00",
    endTime: "17:00",
    clientId: 21,
  },
  {
    id: 22,
    date: "2025-07-04",
    startTime: "11:00",
    endTime: "12:00",
    clientId: 22,
  },
  {
    id: 23,
    date: "2025-07-05",
    startTime: "13:00",
    endTime: "14:00",
    clientId: 23,
  },
  {
    id: 24,
    date: "2025-07-06",
    startTime: "15:00",
    endTime: "16:00",
    clientId: 24,
  },
  {
    id: 25,
    date: "2025-07-07",
    startTime: "09:00",
    endTime: "10:00",
    clientId: 25,
  },
];

export const mockTasks: Task[] = [
  {
    id: 1,
    title: "Тестовое задание",
    taskText: "Описание",
    clientId: 1,
    dueDate: "2025-05-25",
    isComplete: false,
  },
];
